import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  /** TODOリスト */
  const [todos, setTodos] = useState<string[]>([]);
  /** AddのTODO内容 */
  const [tmpTodo, setTmpTodo] = useState("");
  /** 変更中のTODOインデックス */
  const [changeIndex, setChangeIndex] = useState<number>();

  const addTodo = () => {
    if (tmpTodo === "") {
      alert("文字を入力してください");
      return;
    }
    setTodos([...todos, tmpTodo]);
    setTmpTodo("");
  };

  const enableChange = (index: number) => {
    setChangeIndex(index);
  };

  const changeTodo = (index: number, value: string) => {
    const newTodos = [...todos];
    newTodos[index] = value;
    setTodos(newTodos);
  };

  const deleteTodo = (index: number) => {
    const newTodos = todos.filter((todo, todoIndex) => {
      return index !== todoIndex;
    });
    setTodos(newTodos);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>TODOリスト Next.js-TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>TODOリスト</h1>
        <div className="form">
          <input
            type="text"
            name="todo"
            onChange={(e) => setTmpTodo(e.target.value)}
            value={tmpTodo}
          />
          <button onClick={addTodo}>Add</button>
        </div>
        <table>
          <tr>
            <td>TODO</td>
            <td>操作</td>
          </tr>
          {todos.map((todo, index: number) => {
            return (
              <tr key={index}>
                <td>
                  <input
                    type="text"
                    value={todo}
                    disabled={changeIndex !== index}
                    onChange={(e) => changeTodo(index, e.target.value)}
                  ></input>
                </td>
                <td>
                  <button onClick={() => enableChange(index)}>編集</button>
                  <button onClick={() => deleteTodo(index)}>削除</button>
                </td>
              </tr>
            );
          })}
        </table>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
