import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { useState } from "react";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [todos, setTodos] = useState<string[]>([]);

  const [tmpTodo, setTmpTodo] = useState("");

  const addTodo = () => {
    if (tmpTodo === "") {
      alert("文字を入力してください");
      return;
    }
    setTodos([...todos, tmpTodo]);
    setTmpTodo("");
  };

  const deleteTodo = (index: number) => {
    const newTodos = todos.filter((todo, todoIndex) => {
      return index !== todoIndex;
    });
    setTodos(newTodos);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>TODOリスト</h1>
        <div className="form">
          <input
            type="text"
            name="todo"
            onChange={(e) => setTmpTodo(e.target.value)}
            value={tmpTodo}
          />
          <button onClick={addTodo}>Add</button>
        </div>
        <ul>
          {todos.map((todo, index: number) => {
            return (
              <li key={index}>
                {todo}
                <button onClick={() => deleteTodo(index)}>x</button>
              </li>
            );
          })}
        </ul>
        <div>
          <Link href="/changeable">登録・編集・削除バージョンへ</Link>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
